# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_identity_property_1_property_2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=2)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Area', models.IntegerField()),
                ('F_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Property_2')),
            ],
        ),
        migrations.CreateModel(
            name='Houses',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=2, max_digits=2)),
                ('lon', models.DecimalField(decimal_places=2, max_digits=2)),
                ('Area', models.IntegerField()),
                ('Income', models.IntegerField()),
                ('H_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='snippets.Property_1')),
            ],
        ),
    ]
