# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-30 18:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0003_farms_houses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farms',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='farms',
            name='lon',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='houses',
            name='lat',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
        migrations.AlterField(
            model_name='houses',
            name='lon',
            field=models.DecimalField(decimal_places=2, max_digits=5),
        ),
    ]
