# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-13 18:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0004_auto_20170831_0023'),
    ]

    operations = [
        migrations.AddField(
            model_name='farms',
            name='crops',
            field=models.CharField(blank=True, default=b'Rice', max_length=100),
        ),
        migrations.AddField(
            model_name='farms',
            name='lat2',
            field=models.DecimalField(decimal_places=2, default=b'00000', max_digits=5),
        ),
        migrations.AddField(
            model_name='farms',
            name='lon2',
            field=models.DecimalField(decimal_places=2, default=b'00000', max_digits=5),
        ),
    ]
