# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-06 18:26
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0006_auto_20170913_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farms',
            name='lat1',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='lat2',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='lat3',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='lat4',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='lon1',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='lon2',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='lon3',
        ),
        migrations.RemoveField(
            model_name='farms',
            name='lon4',
        ),
        migrations.AddField(
            model_name='farms',
            name='poly',
            field=django.contrib.gis.db.models.fields.PolygonField(default=b'', srid=4326),
        ),
    ]
